env:
  global:
  - secure: YIcRcJLemPREZuRhA1zG+aezvGkLa2jX19EcJxRPzS1Oka8qClM2abIXy1gKtkRMum6OdZCw1BPbV5rpM+LJy8nao3Q/4j1ND3qrp1lEW13nVIozmSQzueePNjhUb2BwwxqBf4XaXLkE7As7PTn8smCXrofVOLPRSDkzmNDVqaE=
  - secure: Pa+Pwr7LAh3feXIpXDMScMfvCwNW5veR9df0Z4ti9GOeoiDW9nbDgJGuq9A5HbkvUElRM/q6h5pCs554cDHzflL2tn4ZmCJsYAMUTIUeEsB4w9w7xjj1icpFH+98Tq68uTmgoyeKXM0ItInCvdQX3uavm5x4L7PmNzpujK0pT+M=

addons:
  sauce_connect: true

before_script:
  - npm install -g se-interpreter

script:
  - se-interpreter ci/travis/interpreter_config.json
